# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Personal Website
email:
description: >- # this means to ignore newlines until "baseurl:"
  A blog about technology and other topics that cross my mind.
github_username: alexwaibel
minimal_mistakes_skin: "dark"
search: true
url: "https://waibel.us"
repository: "alexwaibel/alexwaibel.github.io"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Los_Angeles

comments:
  provider: "giscus"
  giscus:
    repo_id: "R_kgDOLg_CBA"
    category_name: "Blog Post Comments"
    category_id: "DIC_kwDOLg_CBM4CeEMk"
    discussion_term: "pathname"
    reactions_enabled: "1"
    theme: "preferred_color_scheme"

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - nohup.out
  - README.md

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Alex Waibel"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "A software engineer with a life-long passion for technology."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://waibel.us"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/alexwaibel"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/alexwaibel"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
